### ISSUE TITLE
Not adding the value when pressing enter

### ISSUE THREAD

**Issue by Rolando-Barbella** [eranhirs/jsTag#28] opened 2015-08-11 14:35 UTC
Hi there,
Thanks for making this nice project, I would like to know if you can please help with an issue, when I scroll down en select the suggestions with the arrow and then press enter, it doesn't add the full name of the tag, it adds just the number of letters you are typing, my code looks the same to the Twitter's typeahead example you have on the jsTag page demo, any idea why??

**Comment by eranhirs** [comment] 2015-08-12 14:37
Hello!
I didn't quite understand - are you referring a bug in jsTag or in your working environment?
Does this reproduce on the [Demo page] (http://eranhirs.github.io/jsTag/) ?

**Comment by Rolando-Barbella** [comment] 2015-08-13 09:16
Hello!,
Thanks for getting back, the bug doesn't show on the demo page, basically when I type for example a, the drop down menu shows me a number of options,  when I select an option with the  keyboard and press ENTER, it doesn't take the full name of the tag, it only print the letter I type (in this case a).

![tags](https://cloud.githubusercontent.com/assets/6339809/9246328/c66c408a-41a2-11e5-9426-445485aedf04.png)

To be honest I have been a bit confused between jsTag, typehead.js and bloodhound.js so I think the bug doesn't come from your side, sorry about.

**Comment by eranhirs** [comment] 2015-08-13 23:24
To help you I need more technical details and this is not the place, so I'm closing this issue.
I advise you to ask at stackoverflow.com , you can send me a link and I will try to help there.

**Closed by eranhirs** 2015-08-13 23:24 UTC

**Comment by mahaoboy** [comment] 2017-07-05 05:03
Hi @eranhirs @Rolando-Barbella ,
How did you fix the problem?
I am facing the same problem here.

I can see the root cause should be the "enter" keyboard event only was catched by jsTag, not jsTypeAhead. 
Updating the 'breakCodes' to be a different one, not the default 13.
'breakCodes': [
 188 // Comma                                                                                                                                            
   ],

**Comment by YusofBandar** [comment] 2018-08-03 12:56
Hello everyone,

To fix the problem, "when selecting an option with the keyboard and pressing enter it doesn't take the full name of the tag", you have to use angular-typeahead v0.2.1.

angular-typeahead v0.2.1 can be found on the [angular-typeahead repo](https://github.com/Siyfion/angular-typeahead/releases/tag/v0.2.1) or [jsTag demo repo](https://github.com/eranhirs/jsTag/blob/gh-pages/assets/angular-typeahead.js).
